name: 'Mahdi Mazaheri Auto Tagger'
description: 'Automatic tag versioning'
inputs:
  token:
    description: 'git hub token to push the tags'
    required: true
    default: ''
outputs:
  tag:
    description: 'latest version'

runs:
  using: 'node20'
  main: 'index.js'