on: [push]


jobs:
  tag:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    name: tag pushed commit
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: tag
        id: tag
        uses: mazaheriMahdi/auto-tagger-action@v0.0.10
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: latest tag
        run: echo "The Latest version ${{ steps.tag.outputs.tag }}"

    outputs:
      tag: ${{ steps.tag.outputs.tag }}

  create-release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Latest Tag
        run: echo "The latest version is ${{ needs.tag.outputs.tag }}"

      - name: Create a release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ needs.tag.outputs.tag }} # Use the tag output from the previous job
          release_name: Release ${{ needs.tag.outputs.tag }}
          body: |
            Automatically generated release for tag ${{ needs.tag.outputs.tag }}.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}